# username is not email and password can only contain letters and numbers in plaintext


#' get r AuthToken.
#'
#' Get oauth2 login token. Passed to all API requests.
#' @param username_ Robinhood login username. NOT email.
#' @param password_ Robinhood login password. Can only contain letters and numbers in plaintext.
rh_getAuthToken <- function(username_, password_) {
  client_id_ = "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"
  creds <- list(username=username_, password=password_,client_id=client_id_,mfa_code=NULL,grant_type="password")
  res <- httr::POST("https://api.robinhood.com/oauth2/token/", encode = "json", body=creds)
  token <- httr::content(res)$access_token

  ## Old endpoint prior to MFA
  # creds <- list(username=username_, password=password_)
  # res <- POST("https://api.robinhood.com/api-token-auth/", encode = "json", body=creds)
  # token <- content(res)$token

  return(token)
}


#' Create HTTP header.
#'
#' Creates HTTP header to pass into GET HTTP requests. Required for all authentication requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_createAuthHeader <- function(userAuthToken) {
  header <- paste("Bearer ", userAuthToken)
  names(header) <- "Authorization"
  return(header)
}

#' Get account ID.
#'
#' Gets unique robinhood account ID.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountID <- function(account) {
  header <- rh_createAuthHeader(userAuthToken)
  res <- httr::GET("https://api.robinhood.com/user/id", httr::add_headers(.headers=header))
  id <- httr::content(res)$id
  return(id)
}

# Account identifier {account_id} in docs used in api requests
# returns:  accountNumber - 8 digit int
#' Get account number.
#'
#' Gets unique robinhood account number. Used in all account based requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountNumber <- function(account) {
  header <- account$user$authHeader
  res <- httr::GET("https://api.robinhood.com/accounts/", httr::add_headers(.headers=header))
  accountInfo <- httr::content(res)
  accountNumber <- accountInfo$results[[1]]$account_number
  return(accountNumber)
}


#' Get portfolio equity.
#'
#' Returns total portfolio value (equity, cash, and options)
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_getPortfolioEquity <- function(account) {
  header <- account$user$authHeader
  portfolioURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/portfolio/", sep = "")
  res <- httr::GET(portfolioURL, httr::add_headers(.headers=header))
  portfolioEquity <- httr::content(res)$equity
  extendedHours<-httr::content(res)$extended_hours_equity
  if(length(extendedHours)>0){
    if(as.numeric(extendedHours)>=as.numeric(portfolioEquity)){
      portfolioEquity<-extendedHours
    }
  }

  return(portfolioEquity)
}

# Return list of account's options positions
#' Get options positions
#'
#' Return list of account's current options positions.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
# rh_getOptionsPositions <- function(account) {
#   header <- account$user$authHeader
#   positionsURL <- "https://api.robinhood.com/options/positions/"
#   res <- httr::GET(positionsURL, httr::add_headers(.headers=header))
#   positions <- httr::content(res)$results
#   Ticker<-NULL
#   Quantity<-NULL
#   Type<-NULL
#   Price<-NULL
#   for (i in 1:length(positions)){
#     position<-positions[[i]]
#     if (as.numeric(position$quantity)!=0){
#       Ticker<-c(Ticker,position$chain_symbol)
#       Quantity<-c(Quantity,position$quantity)
#       Type<-c(Type,position$type)
#       Price<-c(Price,position$average_price)
#     }
#
#   }
#   Options_Positions<-data.frame(Ticker=Ticker,Quantity=Quantity,Price=Price,Type=Type)
#
#   return(Options_Positions)
# }
