# Install_And_Load <- function(Required_Packages) {
#   Remaining_Packages <- Required_Packages[!(Required_Packages %in% installed.packages()[,"Package"])];
#   if(length(Remaining_Packages))
#   {install.packages(Remaining_Packages);}
#   for(package_name in Required_Packages)
#   {suppressMessages(library(package_name,character.only=TRUE, quietly = TRUE));}
# }
#
# packages<-read.csv("packages.csv",header=FALSE)
# packages<-as.character(packages$V1)
# packages<-packages[-40]
# Install_And_Load(packages)
#
# library(httr)
# library(jsonlite)
# library(XML)
# library(xml2)

##### Robinhood Functions ############################################################################################

## AUTH BASED FUNCTIONS #############################################
# username is not email and password can only contain letters and numbers in plaintext


#' get r AuthToken.
#'
#' Get oauth2 login token. Passed to all API requests.
#' @param username_ Robinhood login username. NOT email.
#' @param password_ Robinhood login password. Can only contain letters and numbers in plaintext.
rh_getAuthToken <- function(username_, password_) {
  client_id_ = "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"
  creds <- list(username=username_, password=password_,client_id=client_id_,mfa_code=NULL,grant_type="password")
  res <- httr::POST("https://api.robinhood.com/oauth2/token/", encode = "json", body=creds)
  token <- httr::content(res)$access_token

  ## Old endpoint prior to MFA
  # creds <- list(username=username_, password=password_)
  # res <- POST("https://api.robinhood.com/api-token-auth/", encode = "json", body=creds)
  # token <- content(res)$token

  return(token)
}




#' Create HTTP header.
#'
#' Creates HTTP header to pass into GET HTTP requests. Required for all authentication requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_createAuthHeader <- function(userAuthToken) {
  header <- paste("Bearer ", userAuthToken)
  names(header) <- "Authorization"
  return(header)
}

#' Get account ID.
#'
#' Gets unique robinhood account ID.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountID <- function(account) {
  header <- rh_createAuthHeader(userAuthToken)
  res <- httr::GET("https://api.robinhood.com/user/id", httr::add_headers(.headers=header))
  id <- httr::content(res)$id
  return(id)
}

# Account identifier {account_id} in docs used in api requests
# returns:  accountNumber - 8 digit int
#' Get account number.
#'
#' Gets unique robinhood account number. Used in all account based requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountNumber <- function(account) {
  header <- account$user$authHeader
  res <- httr::GET("https://api.robinhood.com/accounts/", httr::add_headers(.headers=header))
  accountInfo <- httr::content(res)
  accountNumber <- accountInfo$results[[1]]$account_number
  return(accountNumber)
}


#' Get current positions.
#'
#' Return list of account's current positions in list structure of request.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_getPositions <- function(account) {
  header <- account$user$authHeader
  positionsURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/positions/", sep = "")
  res <- httr::GET(positionsURL, httr::add_headers(.headers=header))
  positions <- httr::content(res)$results
  return(positions)
}

#' Get instrument url.
#'
#' Helper method to get a ticker's instrument url for API requests.
#' @param  ticker equity ticker symbol. Must be capitalized.
#' @param  userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getInstrumentURL <- function(ticker,account) {

  header <- account$user$authHeader

  res <- httr::GET(paste("https://api.robinhood.com/fundamentals/", ticker, "/",sep = ""), httr::add_headers(.headers=header))
  instrumentURL <- httr::content(res)$instrument
  return(instrumentURL)
}


#' Get instrument info.
#'
#' Return list with symbol and name for instrument url
#' @param  instrumentURL instrument url returned by rh_getInstrumentURL.
rh_getInstrumentInfo <- function(instrumentURL) {
  res <- httr::GET(instrumentURL)
  instrumentTicker <- httr::content(res)$symbol
  instrumentName <- httr::content(res)$name
  instrumentInfo <- list()
  instrumentInfo$ticker <- instrumentTicker
  instrumentInfo$name <- instrumentName
  return(instrumentInfo)
}

#' Parse position helper method.
#'
#' Parses position in list structure to be used in creating a positions data.frame.
#' @param  position position list object returned from rh_getPositions.
parsePosition <- function(position) {
  df <- data.frame("name" = rh_getInstrumentInfo(position$instrument)$name, "quantity"= position$quantity, "average_price"= position$average_buy_price)
  rownames(df) <- rh_getInstrumentInfo(position$instrument)$ticker
  return(df)
}

#' Get positions table.
#'
#' Parses current positions into a data.frame.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_createPositionsTable <- function(account) {
  positionsResponse <- rh_getPositions(account)
  position <- positionsResponse[[1]]
  positionsTable <- as.data.frame(do.call(rbind, lapply(positionsResponse, function(x) parsePosition(x))))
  return(positionsTable)
}

#' Get portfolio equity.
#'
#' Returns total portfolio value (equity, cash, and options)
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_getPortfolioEquity <- function(account) {
  header <- account$user$authHeader
  portfolioURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/portfolio/", sep = "")
  res <- httr::GET(portfolioURL, httr::add_headers(.headers=header))
  portfolioEquity <- httr::content(res)$equity
  extendedHours<-httr::content(res)$extended_hours_equity
  if(length(extendedHours)>0){
    if(as.numeric(extendedHours)>=as.numeric(portfolioEquity)){
      portfolioEquity<-extendedHours
    }
  }

  return(portfolioEquity)
}

#' Get daily gains/losses.
#'
#' Returns daily change in portfolio value
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
# rh_getDayPL<-function(account){
#   header <- account$user$authHeader
#   portfolioURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/portfolio/", sep = "")
#   res <- httr::GET(portfolioURL, httr::add_headers(.headers=header))
#   res<-httr::content(res)
#   last_equity<-res$adjusted_equity_previous_close
#   equity<-res$equity
#   if(is.null(equity)){
#     equity<-res$extended_hours_equity
#   }
#   equity<-as.numeric(equity)
#   last_equity<-as.numeric(last_equity)
#   change<-equity-last_equity
#   percent_change<-(change/last_equity)*100
#   days_change<-data.frame("Change($)"=change,"Percent Change"=percent_change)
#   return(days_change)
# }

#' Place immediate buy order.
#'
#' Place an immediate trigger market/limit buy order.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber 8-digit account number generated by rh_getAccountNumber.
#' @param ticker        Equity ticker symbol. All caps string.
#' @param orderType     "market" or "limit"
#' @param orderPrice    numeric limit price (needed for market order because collared on price)
#' @param numShares     number of shares. Numeric class integer only.
rh_placeImmediateBuyOrder <- function(account, ticker, orderType, orderPrice, numShares) {
  header <- account$user$authHeader
  creds = list(
    account = paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/", sep=""),
    instrument = rh_getInstrumentURL(ticker),
    symbol = ticker,
    type = orderType,
    time_in_force = "gtc",
    trigger = "immediate",
    price = orderPrice,
    quantity = numShares,
    side = "buy"
  )
  res <- httr::POST("https://api.robinhood.com/orders/", encode = "json", body=creds, httr::add_headers(.headers=header))
  print(httr::content(res)$state)
  orderStatus <- list()
  orderStatus$order_id <- httr::content(res)$id
  orderStatus$order_state <- httr::content(res)$state
  return(orderStatus)
}

#' Place stop buy order.
#'
#' Place a stop trigger market/limit buy order.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber 8-digit account number generated by rh_getAccountNumber.
#' @param ticker        Equity ticker symbol. All caps string.
#' @param orderType     "market" or "limit"
#' @param orderPrice    numeric limit price (needed for market order because collared on price)
#' @param numShares     number of shares. Numeric class integer only.
#' @param stopPrice     numeric stop price
rh_placeStopBuyOrder <- function(account, ticker, orderType, orderPrice, numShares, stopPrice) {
  header <- account$user$authHeader
  creds = list(
    account = paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/", sep=""),
    instrument = rh_getInstrumentURL(ticker),
    symbol = ticker,
    type = orderType,
    time_in_force = "gtc",
    trigger = "stop",
    price = orderPrice,
    stop_price = stopPrice,
    quantity = numShares,
    side = "buy"
  )
  res <- httr::POST("https://api.robinhood.com/orders/", encode = "json", body=creds, httr::add_headers(.headers=header))
  orderStatus <- list()
  orderStatus$order_id <- httr::content(res)$id
  orderStatus$order_state <- httr::content(res)$state
  return(orderStatus)
}

#' Place stop sell order.
#'
#' Place a stop trigger market/limit sell order.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber 8-digit account number generated by rh_getAccountNumber.
#' @param ticker        Equity ticker symbol. All caps string.
#' @param orderType     "market" or "limit"
#' @param orderPrice    numeric limit price (needed for market order because collared on price)
#' @param numShares     number of shares. Numeric class integer only.
#' @param stopPrice     numeric stop price
rh_placeStopSellOrder <- function(account, ticker, orderType, orderPrice, numShares, stopPrice) {
  header <- account$user$authHeader
  creds = list(
    account = paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/", sep=""),
    instrument = rh_getInstrumentURL(ticker),
    symbol = ticker,
    type = orderType,
    time_in_force = "gtc",
    trigger = "stop",
    price = orderPrice,
    stop_price = stopPrice,
    quantity = numShares,
    side = "sell"
  )
  res <- httr::POST("https://api.robinhood.com/orders/", encode = "json", body=creds, httr::add_headers(.headers=header))
  orderStatus <- list()
  orderStatus$order_id <- httr::content(res)$id
  orderStatus$order_state <- httr::content(res)$state
  return(orderStatus)
}

#' Place immediate sell order.
#'
#' Place an immediate trigger market/limit sell order.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber 8-digit account number generated by rh_getAccountNumber.
#' @param ticker        Equity ticker symbol. All caps string.
#' @param orderType     "market" or "limit"
#' @param orderPrice    numeric limit price (needed for market order because collared on price)
#' @param numShares     number of shares. Numeric class integer only.
rh_placeImmediateSellOrder <- function(account, ticker, orderType, orderPrice, numShares) {
  header <- account$user$authHeader
  creds = list(
    account = paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/", sep=""),
    instrument = rh_getInstrumentURL(ticker),
    symbol = ticker,
    type = orderType,
    time_in_force = "gtc",
    trigger = "immediate",
    price = orderPrice,
    quantity = numShares,
    side = "sell"
  )
  res <- httr::POST("https://api.robinhood.com/orders/", encode = "json", body=creds, httr::add_headers(.headers=header))
  orderStatus <- list()
  orderStatus$order_id <- httr::content(res)$id
  orderStatus$order_state <- httr::content(res)$state
  return(orderStatus)
}



#' Get fundamentals
#'
#' Get summary fundamentals data on company ticker.
#' @param ticker  Equity ticker symbol. All caps string.
rh_getFundamentals<-function(ticker,account){
  ticker<-toupper(ticker)
  header<-account$user$authHeader
  res<-httr::GET(paste("https://api.robinhood.com/fundamentals/",ticker,"/",sep=""), httr::add_headers(.headers=header))
  fundamentals_list<-httr::content(res)
  fundamentals_list<-as.data.frame(fundamentals_list)
  return(fundamentals_list)
}



#' Get option order history
#'
#' Retrieve all options transation history in data.frame
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getOptionsOrders <- function(account) {
  header <- account$user$authHeader

  Price<-NULL
  Premium<-NULL
  State<-NULL
  Quantity<-NULL
  Ticker<-NULL
  Type<-NULL
  cumulative_quantity<-NULL
  Trigger<-NULL
  last_transacted<-NULL
  updated<-NULL
  created<-NULL
  avg_price<-NULL
  stop_price<-NULL
  response_category<-NULL
  Direction<-NULL
  NEXTURL<-"https://api.robinhood.com/options/orders/"
  while(is.null(NEXTURL)!=T){
    res <- httr::GET(NEXTURL, httr::add_headers(.headers=header))
    NEXTURL<-httr::content(res)$`next`

    results<-httr::content(res)$results
    for (i in 1:length(results)) {
      result<-results[[i]]

      if(result$state=="filled"){
        if(result$response_category=="success"||result$response_category=="unknown"){
          State<-c(State,result$state)

          Ticker<-c(Ticker,result$chain_symbol)
          Price<-c(Price,result$price)
          Premium<-c(Premium,result$premium)
          Direction<-c(Direction,result$direction)
          Quantity<-c(Quantity,result$quantity)
          if (is.null(result$opening_strategy)){
            Type<-c(Type,result$closing_strategy)
          }
          else{
            Type<-c(Type,result$opening_strategy)
          }
          updated<-c(updated,result$updated_at)
          created<-c(created,result$created_at)
          response_category<-c(response_category,result$response_category)
          Trigger<-c(Trigger,result$trigger)
        }
      }
    }
  }
  Date<-updated
  ORDERS<-data.frame(Type=Type,Ticker=Ticker,Price=Price,Premium=Premium,Quantity=Quantity,Date=Date,Direction=Direction)
  return(ORDERS)
}

# Return list of account's options positions
#' Get options positions
#'
#' Return list of account's current options positions.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
# rh_getOptionsPositions <- function(account) {
#   header <- account$user$authHeader
#   positionsURL <- "https://api.robinhood.com/options/positions/"
#   res <- httr::GET(positionsURL, httr::add_headers(.headers=header))
#   positions <- httr::content(res)$results
#   Ticker<-NULL
#   Quantity<-NULL
#   Type<-NULL
#   Price<-NULL
#   for (i in 1:length(positions)){
#     position<-positions[[i]]
#     if (as.numeric(position$quantity)!=0){
#       Ticker<-c(Ticker,position$chain_symbol)
#       Quantity<-c(Quantity,position$quantity)
#       Type<-c(Type,position$type)
#       Price<-c(Price,position$average_price)
#     }
#
#   }
#   Options_Positions<-data.frame(Ticker=Ticker,Quantity=Quantity,Price=Price,Type=Type)
#
#   return(Options_Positions)
# }



#' Get the historical quotes for a symbol.
#'
#' @param symbols The shorthand symbols.
#' @param interval The interval: week|day|10minute|5minute
#' @param span The span: day|week|year
#' @param bounds extended|regular|trading
#' @param keep_meta whether to keep meta data. Defaults to FALSE.
#' @param to_xts    whether to convert to xts. Defaults to TRUE.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_historicals <- function(symbols, interval = "day",
                           span = "year", bounds = "regular",
                           keep_meta = FALSE, to_xts = TRUE,account){

  # Get the data
  hist_list <- lapply(X = symbols,
                      function(x){rh_historicals_one(symbol = x,
                                                     interval = interval,
                                                     span = span,
                                                     bounds = bounds,account=account)})

  # Keep only the historical data
  if(!keep_meta){
    hist_list <- lapply(hist_list, function(x) x$historicals[[1]])
  }

  if(to_xts & !keep_meta){

    hist_list <- lapply(hist_list,
                        function(x){
                          x_converted <- xts::xts(x = x[, c("open_price", "close_price", "high_price", "low_price", "volume")],
                                                  order.by = x$begins_at)
                          attr(x_converted, "session") <- x$session
                          attr(x_converted, "interpolated") <- x$interpolated

                          x_converted
                        })
  }

  # name the list.
  names(hist_list) <- symbols

  hist_list
}

#' Historical data helper.
#'
#' @param symbol The shorthand symbols.
#' @param interval The interval: week|day|10minute|5minute
#' @param span The span: day|week|year
#' @param bounds extended|regular|trading
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_historicals_one <- function(symbol, interval = interval, span = span, bounds = bounds,account=account){

  header=account$user$authHeader

  # Create the url
  #' Base url

  rh_base_url <- function(){

    httr::parse_url("https://api.robinhood.com")
  }
  rh_url <- rh_base_url()
  rh_url$path <- paste0("quotes/historicals/", symbol, "/")
  rh_url$query <- list(interval = interval,
                       span = span,
                       bounds = bounds)
  rh_url <- httr::build_url(rh_url)

  # GET the quotes
  quotes_rh <- httr::GET(url = rh_url,httr::add_headers(.headers=header))

  # Check the responce
  if (httr::http_error(quotes_rh)) {
    stop(
      httr::content(x = quotes_rh, as = "text", encoding = "UTF-8"),
      call. = FALSE)
  }

  # parse the content
  content_rh <- httr::content(x = quotes_rh, as = "text", encoding = "UTF-8")
  content_rh <- jsonlite::fromJSON(txt = content_rh)

  meta_rh <- as.data.frame(content_rh[1:6], stringsAsFactors = FALSE)

  hist_rh <- content_rh$historicals
  hist_rh$begins_at <- lubridate::ymd_hms(hist_rh$begins_at,
                                          tz = "UTC")
  hist_rh$open_price <- as.numeric(hist_rh$open_price)
  hist_rh$close_price <- as.numeric(hist_rh$close_price)
  hist_rh$high_price <- as.numeric(hist_rh$high_price)
  hist_rh$low_price <- as.numeric(hist_rh$low_price)

  meta_rh$historicals <- list(hist_rh)

  meta_rh
}
######

# rh_getOptions<-function(symbol,expiration_dates,option_type){
#   header<-rh_createAuthHeader(userAuthToken)
#   chain_id<-"912190a6-ee19-4d47-b7ea-f631c75db650"
#   instrumentURL<-rh_getInstrumentURL(symbol)
#   instrumentID<-strsplit(instrumentURL,"/")[[1]][5]
#
#
#
#   url<-paste0("https://api.robinhood.com/options/chains/?equity_instrument_ids=",instrumentID)
#   res<-GET(url,add_headers(.headers=header))
#   #api_url + "/options/instruments/?chain_id={_chainid}&expiration_dates={_dates}&state=active&tradability=tradable&type={_type}".format(_chainid=chainid, _dates=dates, _type=option_type)
#   result<-content(res)$results
#   strike_price<-NULL
#   state<-NULL
#   urls<-NULL
#   expiration_date<-NULL
#   created_at<-NULL
#   Type<-NULL
#   Ticker<-NULL
#   issue_date<-NULL
#   for (i in 1:length(result)){
#     ##Mostl likely need to iterate through all dimensions of result list
#     chainId<-result[[i]]$id
#     expiration_dates<-as.character(result[[i]]$expiration_dates)
#     chain_url<-paste0("https://api.robinhood.com/options/instruments/?chain_id=",chainId,"&expiration_dates=",expiration_dates[1],"&state=active&tradeability=tradable&type=",option_type)
#     #"/options/instruments/?chain_id={_chainid}&expiration_dates={_dates}&state=active&tradability=tradable&type={_type}".format(_chainid=chainid, _dates=dates, _type=option_type
#     res<-GET(chain_url,add_headers(.headers=header))
#     results<-content(res)$results
#
#
#     for (j in 1:length(results)){
#       result<-results[[j]]
#       issue_date<-c(issue_date,result$issue_date)
#       strike_price<-c(strike_price,result$strike_price)
#       state<-c(state,result$state)
#       urls<-c(urls,result$url)
#       expiration_date<-c(expiration_date,result$expiration_date)
#       created_at<-c(created_at,result$created_at)
#       Type<-c(Type,result$type)
#       Ticker<-c(Ticker,result$chain_symbol)
#     }
#   }
# }

####
# rh_quote<-function(ticker)
