# Install_And_Load <- function(Required_Packages) {
#   Remaining_Packages <- Required_Packages[!(Required_Packages %in% installed.packages()[,"Package"])];
#   if(length(Remaining_Packages))
#   {install.packages(Remaining_Packages);}
#   for(package_name in Required_Packages)
#   {suppressMessages(library(package_name,character.only=TRUE, quietly = TRUE));}
# }
#
# packages<-read.csv("packages.csv",header=FALSE)
# packages<-as.character(packages$V1)
# packages<-packages[-40]
# Install_And_Load(packages)
#
# library(httr)
# library(jsonlite)
# library(XML)
# library(xml2)

##### Robinhood Functions ############################################################################################

## AUTH BASED FUNCTIONS #############################################
# username is not email and password can only contain letters and numbers in plaintext


#' get r AuthToken.
#'
#' Get oauth2 login token. Passed to all API requests.
#' @param username_ Robinhood login username. NOT email.
#' @param password_ Robinhood login password. Can only contain letters and numbers in plaintext.
rh_getAuthToken <- function(username_, password_) {
  client_id_ = "c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS"
  creds <- list(username=username_, password=password_,client_id=client_id_,mfa_code=NULL,grant_type="password")
  res <- httr::POST("https://api.robinhood.com/oauth2/token/", encode = "json", body=creds)
  token <- httr::content(res)$access_token

  ## Old endpoint prior to MFA
  # creds <- list(username=username_, password=password_)
  # res <- POST("https://api.robinhood.com/api-token-auth/", encode = "json", body=creds)
  # token <- content(res)$token

  return(token)
}




#' Create HTTP header.
#'
#' Creates HTTP header to pass into GET HTTP requests. Required for all authentication requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_createAuthHeader <- function(userAuthToken) {
  header <- paste("Bearer ", userAuthToken)
  names(header) <- "Authorization"
  return(header)
}

#' Get account ID.
#'
#' Gets unique robinhood account ID.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountID <- function(account) {
  header <- rh_createAuthHeader(userAuthToken)
  res <- httr::GET("https://api.robinhood.com/user/id", httr::add_headers(.headers=header))
  id <- httr::content(res)$id
  return(id)
}

# Account identifier {account_id} in docs used in api requests
# returns:  accountNumber - 8 digit int
#' Get account number.
#'
#' Gets unique robinhood account number. Used in all account based requests.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getAccountNumber <- function(account) {
  header <- account$user$authHeader
  res <- httr::GET("https://api.robinhood.com/accounts/", httr::add_headers(.headers=header))
  accountInfo <- httr::content(res)
  accountNumber <- accountInfo$results[[1]]$account_number
  return(accountNumber)
}


#' Get current positions.
#'
#' Return list of account's current positions in list structure of request.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_getPositions <- function(account) {
  header <- account$user$authHeader
  positionsURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/positions/", sep = "")
  res <- httr::GET(positionsURL, httr::add_headers(.headers=header))
  positions <- httr::content(res)$results
  return(positions)
}

#' Get instrument url.
#'
#' Helper method to get a ticker's instrument url for API requests.
#' @param  ticker equity ticker symbol. Must be capitalized.
#' @param  userAuthToken oauth2 token generated by rh_getAuthToken.
rh_getInstrumentURL <- function(ticker,account) {

  header <- account$user$authHeader

  res <- httr::GET(paste("https://api.robinhood.com/fundamentals/", ticker, "/",sep = ""), httr::add_headers(.headers=header))
  instrumentURL <- httr::content(res)$instrument
  return(instrumentURL)
}


#' Get instrument info.
#'
#' Return list with symbol and name for instrument url
#' @param  instrumentURL instrument url returned by rh_getInstrumentURL.
rh_getInstrumentInfo <- function(instrumentURL) {
  res <- httr::GET(instrumentURL)
  instrumentTicker <- httr::content(res)$symbol
  instrumentName <- httr::content(res)$name
  instrumentInfo <- list()
  instrumentInfo$ticker <- instrumentTicker
  instrumentInfo$name <- instrumentName
  return(instrumentInfo)
}

#' Parse position helper method.
#'
#' Parses position in list structure to be used in creating a positions data.frame.
#' @param  position position list object returned from rh_getPositions.
parsePosition <- function(position) {
  df <- data.frame("name" = rh_getInstrumentInfo(position$instrument)$name, "quantity"= position$quantity, "average_price"= position$average_buy_price)
  rownames(df) <- rh_getInstrumentInfo(position$instrument)$ticker
  return(df)
}

#' Get positions table.
#'
#' Parses current positions into a data.frame.
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_createPositionsTable <- function(account) {
  positionsResponse <- rh_getPositions(account)
  position <- positionsResponse[[1]]
  positionsTable <- as.data.frame(do.call(rbind, lapply(positionsResponse, function(x) parsePosition(x))))
  return(positionsTable)
}

#' Get portfolio equity.
#'
#' Returns total portfolio value (equity, cash, and options)
#' @param userAuthToken oauth2 token generated by rh_getAuthToken.
#' @param accountNumber account number generated by rh_getAccountNumber.
rh_getPortfolioEquity <- function(account) {
  header <- account$user$authHeader
  portfolioURL <- paste("https://api.robinhood.com/accounts/", account$user$accountNumber, "/portfolio/", sep = "")
  res <- httr::GET(portfolioURL, httr::add_headers(.headers=header))
  portfolioEquity <- httr::content(res)$equity
  extendedHours<-httr::content(res)$extended_hours_equity
  if(length(extendedHours)>0){
    if(as.numeric(extendedHours)>=as.numeric(portfolioEquity)){
      portfolioEquity<-extendedHours
    }
  }

  return(portfolioEquity)
}

